# Fastify API service
FROM node:20-alpine as runtime

WORKDIR /app
RUN apk add --no-cache git=~2

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --non-interactive --ignore-scripts && yarn cache clean

COPY . .

ENV API_PORT=3001

ENV API_HOST=0.0.0.0

EXPOSE 3001

CMD ["yarn", "dev:api"]
