name: Build and push staking widget to dev

run-name: Build and push staking-widget:dev to dev

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - develop
  #   paths-ignore:
  #     - '.github/**'
  #     - 'test/**'

permissions:
  contents: read

jobs:
  build-and-push:
    # if: github.ref_name == 'develop'
    uses: lidofinance/actions/.github/workflows/k8s-build-push-harbor.yml@c7b5b6c5d8013046347d728d748fa741eb214e28
    with:
      tag: dev
      registry: registry.dev.k8s-dev.org
      registry_username: ${{ vars.REGISTRY_USERNAME }}
      image: team-si/staking-widget
      environment: harbor_dev_release
      dockerfile: Dockerfile.k8s
    secrets:
      registry_token: ${{ secrets.HARBOR_DEV_TOKEN }}
