name: CI Preview stand deploy

on:
  workflow_dispatch:
  pull_request:
    types:
      [opened, synchronize, reopened, ready_for_review]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false }}
    name: Build and deploy
    outputs:
      stand_url: ${{ steps.stand.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Preview stand deploying
        uses: lidofinance/dispatch-workflow@v1
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          TARGET_REPO: "lidofinance/infra-mainnet"
          TARGET: ${{ github.head_ref }}
          TARGET_WORKFLOW: "preview_stand_deploy.yaml"
          INPUTS_REPO_NAME: ${{ github.repository }}
          INPUTS_PR_ID: ${{ github.event.pull_request.number }}

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        if: always()
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: Preview stand status

      - name: Extract stand url
        if: always()
        run: echo "##[set-output name=url;]$(echo '${{ steps.fc.outputs.comment-body }}' | grep -Eo 'https?://[^ >]+')"
        id: stand
