name: CI Preview stand deploy

on:
  workflow_dispatch:
    inputs:
      inventory:
        description: inventory to be used for preview stand deploying
        default: testnet
        required: false
        type: choice
        options:
          - staging
          - testnet

  pull_request:
    types:
      [opened, synchronize, reopened, ready_for_review]
    branches-ignore:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false }}
    name: Build and deploy
    outputs:
      stand_url: ${{ steps.stand.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - uses: lidofinance/gh-find-current-pr@v1
        id: pr

      - name: Set ref
        id: ref
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Preview stand deploying
        uses: lidofinance/dispatch-workflow@v1
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          TARGET_REPO: "lidofinance/infra-mainnet"
          TARGET: ${{ github.head_ref || steps.ref.outputs.short_ref }}
          TARGET_WORKFLOW: "preview_stand_deploy.yaml"
          INPUTS_REPO_NAME: ${{ github.repository }}
          INPUTS_PR_ID: ${{ steps.pr.outputs.number }}
          INPUTS_INVENTORY: "${{ inputs.inventory || 'testnet' }}"

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        if: always()
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: Preview stand status

      - name: Extract stand url
        if: always()
        run: echo "##[set-output name=url;]$(echo '${{ steps.fc.outputs.comment-body }}' | grep -Eo 'https?://[^ >]+')"
        id: stand


  tests:
    needs: deploy
    if: ${{ github.event.pull_request.draft == false }}
    uses: ./.github/workflows/tests.yml
    secrets: inherit
    with:
      stand_url: ${{ needs.deploy.outputs.stand_url }}
      stand_type: "${{ inputs.inventory }}"
      on_preview_stand: true
