name: CI Staging

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
      - '.github/**'

jobs:
# test:
#   ...
  deploy:
    runs-on: ubuntu-latest
    # needs: test
    name: Build and deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Staging deploying
        run: .github/dispatch_workflow.py
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          TARGET_REPO: "${{ secrets.TARGET_REPO }}"
          TARGET_WORKFLOW: "deploy_staging_mainnet_staking_widget_ts.yaml"
