name: CI Staging

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'test/**'

permissions:
  contents: read

jobs:
  # test:
  #   ...

  deploy:
    runs-on: ubuntu-latest
    # needs: test
    name: Build and deploy
    steps:
      - name: Staging deploy
        uses: lidofinance/dispatch-workflow@v1
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          TARGET_REPO: 'lidofinance/infra-mainnet'
          TARGET_WORKFLOW: 'deploy_staging_critical_ethereum_staking_widget.yaml'
          TARGET: 'main'

  tests:
    needs: deploy
    if: ${{ github.event.pull_request.draft == false }}
    uses: ./.github/workflows/tests.yml
    secrets: inherit
    with:
      stand_url: https://stake.infra-staging.org
      stand_type: staging-critical
